### ISSUE TITLE
ImportError: cannot import name 'get_entries' from 'doped.chemical_potentials' 

### ISSUE THREAD

**Issue by kuazhangge** [SMTG-Bham/doped#100]
Hello. I've encountered the following problem in the "Full Defect Workflow Example (w/GGA)" tutorial. I've checked the "chemical_potentials.py" file, but didn't find "get_entries" in it. Could you please tell me how to solve this?
![image](https://github.com/user-attachments/assets/d0389bc9-adca-4706-8412-c3209e8e43a2)

**Comment by kuazhangge** [comment]
> Hi @kuazhangge! Thanks for flagging this. Apologies for this. The notebook was updated recently to use code from the `doped` `develop` branch which is very nearly ready to be released for the latest version of `doped`, but then I was swarmed by deadlines this last month and so this was delayed. The latest version will be released in the next month or I will die trying.
> 
> For now, you can either `git clone` and install the latest `develop` branches of `doped` and `ShakeNBreak` to use this code, or look at the docs version matching the latest release (`2.4.7`) here: https://doped.readthedocs.io/en/latest/Installation.html#developer-installation
> 
> You can select the version of the docs using these buttons on readthedocs: <img alt="image" width="282" src="https://private-user-images.githubusercontent.com/51478689/396227751-fe30e7f6-0eb6-4eac-965f-3ccb1da1f612.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MjE5OTQsIm5iZiI6MTczNDUyMTY5NCwicGF0aCI6Ii81MTQ3ODY4OS8zOTYyMjc3NTEtZmUzMGU3ZjYtMGViNi00ZWFjLTk2NWYtM2NjYjFkYTFmNjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDExMzQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5NzVlYTYyODcxNTU2NWQ4MmVkMWE4OTk4N2JlZTY0MWNhMGVjZDA3NzMxOTExNjg2YTM2YTM3ZDcwMTM3YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Y3MP7rEU9sZnNAl4cWIquWE4ru7d-cvxdNb9GiyqMQA">
> 
> The tutorial notebooks on the `doped` `main` branch match that of the latest release too btw: https://github.com/SMTG-Bham/doped/tree/main/examples

Thank you very much for your reply. If possible, please do it as soon as you can, because there seem to be quite a lot of problems. 
![~EDB~IMV(_NE2}7 GZ1F4SJ](https://github.com/user-attachments/assets/9b7aa4aa-f84d-42fc-a6a5-ccd77c2aa18e)
By the way, there's something wrong with my Materials Project (MP) API. I'm using an old version of the API key. The message displayed in Chinese is "The remote host forcibly closed an existing connection." If you know how to solve this problem, please let me know.
![image](https://github.com/user-attachments/assets/c6556616-3226-4d3b-a8f1-949974d497d9)

**Comment by kavanase** [comment]
Hi @kuazhangge, it seems to be some problem with your internet connection to the MP API. 
There can sometimes be issues with accessing from certain countries I think, but usually just temporary. I'd suggest trying again or looking online for other solutions – this is a pymatgen/Materials Project problem and not a `doped` issue

**Comment by kavanase** [comment]
Hi @kuazhangge, just fyi, the latest versions of `doped` and `ShakeNBreak` have just been released, including a lot of efficiency updates and many additional features (some of which are exemplified in the tutorials). You can see the [release notes](https://doped.readthedocs.io/en/latest/changelog_link.html) for more info and update with `pip install -U doped shakenbreak`

**Comment by kuazhangge** [comment]
> Hi [@kuazhangge](https://github.com/kuazhangge), just fyi, the latest versions of `doped` and `ShakeNBreak` have just been released, including a lot of efficiency updates and many additional features (some of which are exemplified in the tutorials). You can see the [release notes](https://doped.readthedocs.io/en/latest/changelog_link.html) for more info and update with `pip install -U doped shakenbreak`

Thank you very much for the update. I'd like to ask if there is any code in doped for handling parameters related to solar cells. I went through the entire doped tutorial, but it seems that I couldn't find any.

**Comment by kavanase** [comment]
Hi @kuazhangge, it depends what 'solar cell parameters' you mean. You can calculate defect concentrations, transition level positions and carrier concentrations with `doped` (see e.g. the thermodynamics tutorials), which are very relevant to solar cell operation. But if you want to go beyond this, you can calculate non-radiative capture coefficients with e.g. [CarrierCapture.jl](https://wmd-group.github.io/CarrierCapture.jl/dev/) or [nonrad](https://nonrad.readthedocs.io/en/latest/), and use e.g. [TLC](https://traplimitedconversion.readthedocs.io/) to estimate the effect of this on solar cell efficiency.
I'd suggest these references, where those tools are used:
- https://chemrxiv.org/engage/chemrxiv/article-details/6706a93612ff75c3a1f8c995
- https://pubs.acs.org/doi/10.1021/acsenergylett.1c00380
- https://www.cell.com/joule/fulltext/S2542-4351(24)00204-6?rss=yes

**Comment by kuazhangge** [comment]
> Hi [@kuazhangge](https://github.com/kuazhangge), it depends what 'solar cell parameters' you mean. You can calculate defect concentrations, transition level positions and carrier concentrations with `doped` (see e.g. the thermodynamics tutorials), which are very relevant to solar cell operation. But if you want to go beyond this, you can calculate non-radiative capture coefficients with e.g. [CarrierCapture.jl](https://wmd-group.github.io/CarrierCapture.jl/dev/) or [nonrad](https://nonrad.readthedocs.io/en/latest/), and use e.g. [TLC](https://traplimitedconversion.readthedocs.io/) to estimate the effect of this on solar cell efficiency. I'd suggest these references, where those tools are used:
> 
> * https://chemrxiv.org/engage/chemrxiv/article-details/6706a93612ff75c3a1f8c995
> * https://pubs.acs.org/doi/10.1021/acsenergylett.1c00380
> * https://www.cell.com/joule/fulltext/S2542-4351(24)00204-6?rss=yes

Yes, I'd like to calculate the carrier capture coefficients and draw the graph shown below. Your answer has been very helpful to me. Thank you so much.

![Image](https://github.com/user-attachments/assets/cecc5b80-f7d9-49de-83f0-62dd868b6d56)
