### ISSUE TITLE
JOSS review issues #1

### ISSUE THREAD

**Issue by yuan-gist** [SMTG-Bham/doped#55]
**I will ad a number of issues seen from Review by tomorrow. There are just minor issues.**

In this issue, I used `doped` to parse my old calculations (trying to use doped to get degeneracy factors for defect densities):
`CaO_bulk  v_Ca_0  v_Ca_+1  v_Ca_-1  v_Ca_-2`

The jupyter-notebook is found: https://github.com/yuan-gist/doped_review/blob/main/doped.ipynb

The calculations are found: the file sizes are too large, can I put on Google drive and share via email?

The issue is that it seems ` v_Ca_+1 ` is not parsed. I also tested other cases. it seems only one type charge states can be parsed.

**Comment by kavanase** [comment]
Hi @yuan-gist,
Thanks for raising, that's odd! I haven't seen this issue before (and in general `DefectsParser` should warn if any defects haven't been successfully parsed and why.
Yes if you could share the output files to reproduce that would be great. 
Emailing a Google drive / Dropbox /OneDrive link is perfect. 
Just to note, doped can parse gzipped files (`vasprun.xml.gz` etc) to save space (so could possibly also just upload to your GitHub repo as this, as the max file size when uploaded by the CLI is 100 Mb which I guess should be enough?
Thanks!

**Comment by yuan-gist** [comment]
I emailed the Google drive link. Thanks!

**Comment by kavanase** [comment]
Hi @yuan-gist, just to check, I didn't get any email yet. Maybe it bounced for some reason, or wasn't the correct address?
My email is `s.kavanagh19 [at] imperial.ac.uk`

**Comment by kavanase** [comment]
Hi @yuan-gist, email now received!
Looking at the folder structure you sent, I can spot the issue.
So in all your defect folders except `v_Ca_+1`, the defect output is in the `vasp_gam` subfolder. As you see when you run `doped`'s `DefectsParser`, it automatically detects `vasp_gam` as the appropriate subfolder (with the most amount of VASP output files present across the defect directories – but of course this can also be manually controlled with the `subfolder` parameter), and so it only parsed the `v_Cd_X/vasp_gam` folders, and so does not detect `v_Cd_+1` as a defect folder.

<img width="971" alt="image" src="https://github.com/SMTG-Bham/doped/assets/51478689/90dca333-ea15-439d-ae66-dabf99d3d213">

If you make the same `vasp_gam` folder for `v_Ca_+1` and move the output file to this directory, it will be correctly parsed. Alternatively you can use no subfolder for each defect folder (or any other sub-folder name, as long as it's consistent with all defect folders), and `doped` will automatically detect this and parse as appropriate. Hope this answers your query! 😃

**Comment by kavanase** [comment]
Note that for the bulk, it can be with or without a subfolder (as you have here)

**Comment by yuan-gist** [comment]
Ahhh, did not notice and I should have checked . Anyway, thanks a lot, I learned `can use no subfolder for each defect folder`.
