### ISSUE TITLE
Make `CalcResults`/eFNV corrections without `vise.yaml`

### ISSUE THREAD

**Issue by kavanase** [SMTG-Bham/doped#66]
@goodwilling just fyi, I noticed you opened an issue in `pydefect` about making the `pydefect` `CalcResults` object without needing a `vise.yaml` file. In case it's useful, we do this in our `doped` codebase, see e.g. https://github.com/SMTG-Bham/doped/blob/2ec47906f35956329974fcfccc16a4dcea294353/doped/corrections.py#L420

**Comment by kuazhangge** [comment]
> @goodwilling just fyi, I noticed you opened an issue in `pydefect` about making the `pydefect` `CalcResults` object without needing a `vise.yaml` file. In case it's useful, we do this in our `doped` codebase, see e.g.
> 
> https://github.com/SMTG-Bham/doped/blob/2ec47906f35956329974fcfccc16a4dcea294353/doped/corrections.py#L420
Hello. I am using the doped tutorial Defect Calculation Parsing. Regarding this tutorial, when I run the code, it gets stuck on one screen and doesn't load. Moreover, when I directly interrupt the running, it shows that the vise.yaml file cannot be found. What's going on with this?
![H%4 G$ DXN23N@(X{ALYI1I](https://github.com/user-attachments/assets/913ce306-29a3-4b41-b45c-67475a4233bc)
![789 EHZGEFCWG 4ON{JISA](https://github.com/user-attachments/assets/8f78b2b7-b6be-4a96-a8d1-5e41dc1f9d62)
