### ISSUE TITLE
How to generate a specific type of  defect? 

### ISSUE THREAD

**Issue by WangSimin123456** [SMTG-Bham/doped#78]
Hi everyone,

I'm a new user of doped. I want to generate a specific type of defect. For example, my system is a silicon crystal, and I only want to create silicon vacancy defects. I used commands like this:

from pymatgen.core.structure import Structure
from doped.generation import DefectsGenerator
from shakenbreak.input import Distortions

bulk = Structure.from_file("POSCAR")
defect_gen = DefectsGenerator(bulk)
defect_gen.defects = ({'defect_type': ['v_Si']})
Dist = Distortions(defect_gen)
defects_dict, distortion_metadata = Dist.write_vasp_files({"EDIFF": "1e-06", "ENCUT": "500", "NELM": "200", "NSW" : "1000", "LHFCALC": "False", "NUPDOWN": "-1", "LASPH": "False"})

strangely, the line "defect_gen.defects = ({'defect_type': ['v_Si']})" seems not work and it generated interstitial defects at the same time. Can you help me to solve this problem? Thanks.

**Comment by WangSimin123456** [comment]
And when the system is complex, it would take long time to calculate the interstitial position like this:

_Loading vasp/6.3.2-nvhpc-23.9-mpi
  Loading requirement: tbb/latest compiler-rt/latest mkl/2022.0.2 nvhpc/23.9
Generating substitutions: 25.0%|██▌       | [00:08,   2.27it/s]generation.py:1435: UserWarning: 
Specified 'extrinsic' elements ['Si'] are present in the host structure, so do not need to be specified as 'extrinsic' in DefectsGenerator(). These will be ignored.
Generating DefectEntry objects: 100.0%|██████████| [3:37:13,  130.34s/it] 
input.py:756: UserWarning: Multiplicity of interstitial at site [0.368 0.479 0.618] could not be determined from Voronoi analysis. Multiplicity set to 1.
input.py:756: UserWarning: Multiplicity of interstitial at site [0.372 0.366 0.526] could not be determined from Voronoi analysis. Multiplicity set to 1.
input.py:756: UserWarning: Multiplicity of interstitial at site [0.446 0.06  0.945] could not be determined from Voronoi analysis. Multiplicity set to 1.
input.py:756: UserWarning: Multiplicity of interstitial at site [0.708 0.041 0.544] could not be determined from Voronoi analysis. Multiplicity set to 1.
input.py:756: UserWarning: Multiplicity of interstitial at site [0.582 0.282 0.881] could not be determined from Voronoi analysis. Multiplicity set to 1.
input.py:756: UserWarning: Multiplicity of interstitial at site [0.11  0.121 0.21 ] could not be determined from Voronoi analysis. Multiplicity set to 1.
input.py:756: UserWarning: Multiplicity of interstitial at site [0.538 0.735 0.037] could not be determined from Voronoi analysis. Multiplicity set to 1.
input.py:756: UserWarning: Multiplicity of interstitial at site [0.884 0.453 0.135] could not be determined from Voronoi analysis. Multiplicity set to 1.
input.py:756: UserWarning: Multiplicity of interstitial at site [0.111 0.05  0.278] could not be determined from Voronoi analysis. Multiplicity set to 1.
input.py:756: UserWarning: Multiplicity of interstitial at site [0.034 0.806 0.635] could not be determined from Voronoi analysis. Multiplicity set to 1.
input.py:756: UserWarning: Multiplicity of interstitial at site [0.653 0.03  0.508] could not be determined from Voronoi analysis. Multiplicity set to 1.
input.py:756: UserWarning: Multiplicity of interstitial at site [0.376 0.22  0.696] could not be determined from Voronoi analysis. Multiplicity set to 1.
input.py:756: UserWarning: Multiplicity of interstitial at site [0.536 0.807 0.126] could not be determined from Voronoi analysis. Multiplicity set to 1.
input.py:756: UserWarning: Multiplicity of interstitial at site [0.368 0.3   0.127] could not be determined from Voronoi analysis. Multiplicity set to 1.
input.py:756: UserWarning: Multiplicity of interstitial at site [0.955 0.292 0.876] could not be determined from Voronoi analysis. Multiplicity set to 1.
input.py:756: UserWarning: Multiplicity of interstitial at site [0.803 0.358 0.626] could not be determined from Voronoi analysis. Multiplicity set to 1.
input.py:756: UserWarning: Multiplicity of interstitial at site [0.285 0.802 0.39 ] could not be determined from Voronoi analysis. Multiplicity set to 1.
input.py:756: UserWarning: Multiplicity of interstitial at site [0.972 0.645 0.535] could not be determined from Voronoi analysis. Multiplicity set to 1.
input.py:756: UserWarning: Multiplicity of interstitial at site [0.562 0.889 0.221] could not be determined from Voronoi analysis. Multiplicity set to 1.
input.py:756: UserWarning: Multiplicity of interstitial at site [0.875 0.401 0.717] could not be determined from Voronoi analysis. Multiplicity set to 1.
input.py:756: UserWarning: Multiplicity of interstitial at site [0.711 0.428 0.612] could not be determined from Voronoi analysis. Multiplicity set to 1.
input.py:756: UserWarning: Multiplicity of interstitial at site [0.943 0.448 0.037] could not be determined from Voronoi analysis. Multiplicity set to 1.
input.py:756: UserWarning: Multiplicity of interstitial at site [0.799 0.035 0.285] could not be determined from Voronoi analysis. Multiplicity set to 1._

How can it avoid the calculations for interstitial defects and directly generate the vacancy defects?

**Comment by kavanase** [comment]
Hi @WangSimin123456 
For your first question:
> strangely, the line "defect_gen.defects = ({'defect_type': ['v_Si']})" seems not work and it generated interstitial defects at the same time. Can you help me to solve this problem?

Yes this is because when you feed the `DefectsGenerator` object direct to ShakeNBreak's `Distortions` class like you show there (`Dist = Distortions(defect_gen)`), it uses the `DefectEntry` objects which are in the `DefectsGenerator.defect_entries` attribute dict. In general, `doped` and `ShakeNBreak` work off the `DefectEntry` rather than `Defect` objects, as they have defined supercells and other parameters, whereas the `Defect` objects are just a simple representation of the defect in the host _primitive_ cell. So you can edit this parameter if you want to sub-select defects in this way.

Alternatively, what would be a better approach would be to just provide the `DefectEntry` objects you want to use directly to the `Distortions` class, as this can take single `DefectEntry`s or a list of `DefectEntry`s as input (as well as the `DefectsGenerator` object itself), as discussed in the docstring, on the API docs [here](https://shakenbreak.readthedocs.io/en/latest/ShakeNBreak_Example_Workflow.html#generating-distorted-structures) and the ShakeNBreak tutorial [here](https://shakenbreak.readthedocs.io/en/latest/ShakeNBreak_Example_Workflow.html#generating-distorted-structures)

**Comment by kavanase** [comment]
For the second question, yes defect generation can take a lot of time for low symmetry systems. 

For avoiding interstitial generation, you can set `interstitial_gen_kwargs = False` with `DefectsGenerator`, which will skip interstitial generation entirely. This is mention in the `doped` generation tutorial [here](https://doped.readthedocs.io/en/latest/generation_tutorial.html#defect-generation) and in the API docs [here](https://doped.readthedocs.io/en/latest/doped.generation.html#doped.generation.DefectsGenerator) and in the docstring for `DefectsGenerator`. Please check the tutorials and code docstrings (help messages) for the functionality of `doped` first, we have worked hard to make these as clear as possible to save you time.

In general the defect generation steps in `doped` are already heavily optimised (taking advantage of symmetries, folding down to the primitive for generation before transforming back to the supercell, smart algorithms etc). For complex systems, the identification of all the symmetry-inequivalent defect sites in a structure is just fundamentally a computationally challenging issue. 

If you do still need/want to speed this step up, you can also take advantage of `doped`'s multiprocessing functionality. By default, `doped` will use nearly all available CPUs to do defect generation with multiprocessing (which can be further controlled by the `processes` argument which like everything else is detailed on the API docs, docstrings and tutorials). So if you run the defect generation on a laptop with more CPUs, or on a HPC, it will run a lot faster.

I suspect the case you show there is some distorted Si supercell, which then makes basically every site in the supercell symmetry-inequivalent. This may be what you are aiming for, but just to be aware this may not be what you want to do if it's just for calculating the intrinsic defects of bulk Si.

**Comment by WangSimin123456** [comment]
Your reply helps me a lot. Thank you very much. When I used "DefectsGenerator.defect_entries" attribute to specify the defects, I encountered such error:

The number in the Wyckoff label is the site multiplicity/degeneracy of that defect in the conventional ('conv.') unit cell, which comprises 1 formula unit(s) of FeSi216.
Note that Wyckoff letters can depend on the ordering of elements in the conventional standard structure, for which doped uses the spglib convention.
Traceback (most recent call last):
  File "/data/home/wangsimin/a_project/333/fe/vacancy/structure_prediction/step2/Fe_i_D3d_0/Bond_Distortion_0.0%/test3/gen.py", line 9, in <module>
    Dist = Distortions(defect_gen)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/software/anaconda3/envs/shakenbreak/lib/python3.11/site-packages/shakenbreak/input.py", line 1764, in __init__
    self.defects_dict = {
                        ^
  File "/public/software/anaconda3/envs/shakenbreak/lib/python3.11/site-packages/shakenbreak/input.py", line 1765, in <dictcomp>
    name.rsplit("_", 1)[0]: [  # name without charge
                            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/software/anaconda3/envs/shakenbreak/lib/python3.11/site-packages/shakenbreak/input.py", line 1768, in <listcomp>
    if defect_entry.name.rsplit("_", 1)[0] == name.rsplit("_", 1)[0]
       ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'name'

And my codes are:

from pymatgen.core.structure import Structure
from doped.generation import DefectsGenerator
from shakenbreak.input import Distortions

bulk = Structure.from_file("POSCAR")
defect_gen = DefectsGenerator(bulk, interstitial_gen_kwargs = False)
#defect_gen.remove_charge_states(defect_entry_name="v_Si", charge_states=[+1, -1])
defect_gen.defect_entries = ({'defect_species': 'v_Si_0'})
Dist = Distortions(defect_gen)

I tried a lot to solve this problem. However, everything seemed to be in vain, and I failed again and again. Can you tell me how to set the "DefectsGenerator.defect_entries" attribute? In fact, I am confused about "with …… and supercell properties" in the manul:

Type
:
dictdefect_entries[](https://doped.readthedocs.io/en/latest/doped.generation.html#doped.generation.DefectsGenerator.defect_entries)
Dictionary of {defect_species: DefectEntry} for all defect entries (with charge state and supercell properties) generated.

Type
:
dict

**Comment by kavanase** [comment]
The issue here is your `defect_entries` format. It should match the original format of `DefectsGenerator.defect_entries`, which is a dictionary with defect names (`string`s) as keys and `DefectEntry`s as the objects. e.g. for selecting the neutral silicon vacancy like you're trying to do here, it should just be:
```python
defect_gen.defect_entries = {'v_Si_0': defect_gen.defect_entries['v_Si_0']}
```
or equivalently if we want to be fancy / allow easier customisation:
```python
defect_gen.defect_entries = {k:v for k,v in defect_gen.defect_entries.items() if k.startswith('v_Si_0')}
```

Of course, you also just do what I mentioned here:
> Alternatively, what would be a better approach would be to just provide the DefectEntry objects you want to use directly to the Distortions class, as this can take single DefectEntrys or a list of DefectEntrys as input (as well as the DefectsGenerator object itself), as discussed in the docstring, on the API docs [here](https://shakenbreak.readthedocs.io/en/latest/ShakeNBreak_Example_Workflow.html#generating-distorted-structures) and the ShakeNBreak tutorial [here](https://shakenbreak.readthedocs.io/en/latest/ShakeNBreak_Example_Workflow.html#generating-distorted-structures)

with e.g.
```python
defect_entry = defect_gen.defect_entries['v_Si_0']
Dist = Distortions(defect_entry)
```
