### ISSUE TITLE
Issue in graphing Intrinsic interstitial defects 

### ISSUE THREAD

**Issue by Atefeh-Yadegarifard** [SMTG-Bham/doped#81]
Dear Doped developers. 
Hello. 
I have been trying to graph the defect formation energy of intrinsic interstitial defects of CsPbI3 with Doped (I generated the POSCAR files with Doped as well). However, even though all of the defect calculations are in one folder, the graph does not show them all, and also shows a wrong legend for some of the defects. 

this is the code :

`from doped.analysis import DefectsParser
from doped.chemical_potentials import CompetingPhasesAnalyzer
from doped.chemical_potentials import CompetingPhases
from monty.serialization import dumpfn, loadfn
import matplotlib.colors as mcolors
from matplotlib.patches import Rectangle
import matplotlib.pyplot as plt
%matplotlib inline 

''' Parsing the defects '''
dielectric = 6.4 
dp = DefectsParser("./doped_intrinsic_scf/interstitial",bulk_path="./doped_pvk_vasp_largerkpts_scf/pristine",dielectric=dielectric)

''' Save the parsed defect entery to a json file '''
dumpfn(dp.defect_dict, fn=f"intrinsic_defect_dict.json")  

''' Calculating the chemical potentials, and saving the competing phase energies as CSV '''
cpa = CompetingPhasesAnalyzer("CsPbI3")
cpa.from_vaspruns(path='./doped_intrinsic_competing_phases/')
cpa.from_vaspruns(path='./doped_intrinsic_competing_phases/',csv_path="./chemical_potentials/intrinsic_interstitial_competing_phase_energies.csv")
chempots = cpa.chempots

''' Saving the chemical potentials as json file '''
dumpfn(cpa.chempots, fn=f"./chemical_potentials/intrinsic_interstitial_chempots.json")

''' Calculating defect formation enrgies, transition levels and plots '''

''' Plot '''
cspbi3_thermo= dp.get_defect_thermodynamics(chempots=chempots)
plot = cspbi3_thermo.plot(limit="Pb-poor",xlim=(-1, 2.5), ylim=(-10.0, 2.0),chempot_table=False)
ax = plt.gca()
ax.set_title("")
plot.suptitle(f"Intrinsic interstitial defects of CsPbI₃",fontsize=8)
ax.set_xlabel("Fermi Level (eV)", fontsize=8)
ax.set_ylabel("Formation Energy (eV)", fontsize=8)
for spine in ax.spines.values():
    spine.set_linewidth(0.5)  # Set the desired line width
        

plot.savefig ("plots/intrinsic_interstitial_cspbi3.png", bbox_inches = 'tight')

'''Defect formation energies '''
formation_energy=cspbi3_thermo.get_formation_energies(limit="Pb-poor")
print (formation_energy)
formation_energy.to_csv("formation_energy_tables/intrinsic_interstitial_Formation_Energies_Pb_poor.csv", index=False,encoding='utf-8-sig')

''' Transition levels '''
transition_levels = cspbi3_thermo.get_transition_levels(all=True)
transition_levels.to_csv("transition_level_tables/intrinsic_interstitial_transition_levels_Pb_poor.csv", index=False,encoding='utf-8-sig')`

and these are the folders that are parsed after the code runs: 
0   ./doped_intrinsic_scf/interstitial/Cs_i_C3v_+1/.  
1    ./doped_intrinsic_scf/interstitial/Cs_i_C3v_0/.  
2   ./doped_intrinsic_scf/interstitial/Cs_i_D4h_+1/.  
3    ./doped_intrinsic_scf/interstitial/Cs_i_D4h_0/.  
4   ./doped_intrinsic_scf/interstitial/Pb_i_C3v_+2/.  
5   ./doped_intrinsic_scf/interstitial/Pb_i_C3v_+1/.  
6      ./doped_intrinsic_scf/interstitial/Pb_i_C3v/.  
7   ./doped_intrinsic_scf/interstitial/Pb_i_D4h_+2/.  
8   ./doped_intrinsic_scf/interstitial/Pb_i_D4h_+1/.  
9    ./doped_intrinsic_scf/interstitial/Pb_i_D4h_0/.  
10   ./doped_intrinsic_scf/interstitial/I_i_C3v_+1/.  
11      ./doped_intrinsic_scf/interstitial/I_i_C3v/.  
12   ./doped_intrinsic_scf/interstitial/I_i_C3v_-1/.  
13   ./doped_intrinsic_scf/interstitial/I_i_D4h_+1/.  
14      ./doped_intrinsic_scf/interstitial/I_i_D4h/.  
15   ./doped_intrinsic_scf/interstitial/I_i_D4h_-1/.  
0   ./doped_intrinsic_scf/interstitial/Cs_i_C3v_+1/.  
1    ./doped_intrinsic_scf/interstitial/Cs_i_C3v_0/.  
2   ./doped_intrinsic_scf/interstitial/Cs_i_D4h_+1/.  
3    ./doped_intrinsic_scf/interstitial/Cs_i_D4h_0/.  
4   ./doped_intrinsic_scf/interstitial/Pb_i_C3v_+2/.  
5   ./doped_intrinsic_scf/interstitial/Pb_i_C3v_+1/.  
6      ./doped_intrinsic_scf/interstitial/Pb_i_C3v/.  
7   ./doped_intrinsic_scf/interstitial/Pb_i_D4h_+2/.  
8   ./doped_intrinsic_scf/interstitial/Pb_i_D4h_+1/.  
9    ./doped_intrinsic_scf/interstitial/Pb_i_D4h_0/.  
10   ./doped_intrinsic_scf/interstitial/I_i_C3v_+1/.  
11      ./doped_intrinsic_scf/interstitial/I_i_C3v/.  
12   ./doped_intrinsic_scf/interstitial/I_i_C3v_-1/.  
13   ./doped_intrinsic_scf/interstitial/I_i_D4h_+1/.  
14      ./doped_intrinsic_scf/interstitial/I_i_D4h/.  
15   ./doped_intrinsic_scf/interstitial/I_i_D4h_-1/.  

however, the final graphs lacks some of the defects or shows wrong legends. This problem does not occur if the defects are graphed separately. 

![intrinsic_interstitial_cspbi3](https://github.com/SMTG-Bham/doped/assets/141133743/4736c255-67f4-422c-8b2a-59d95e3717e5)

**Comment by ireaml** [comment]
Hi Atefeh,

First, note that all your formation energies are negative in that plot, which often indicates an issue in the calculations - maybe in the chemical potentials.

Second, for the missing defects in the plot, it's likely that they have relaxed to very similar structures and so they are grouped in the plot as the same defect (e.g. could be the case for I_i_D4h and I_i_C3v). As explained in the [docs](https://doped.readthedocs.io/en/latest/doped.analysis.html#doped.analysis.DefectsParser.get_defect_thermodynamics), you can avoid this by reducing the parameter `dist_tol` (see detailed description in the [docs](https://doped.readthedocs.io/en/latest/doped.analysis.html#doped.analysis.DefectsParser.get_defect_thermodynamics)). 

For the wrong legends, I would guess that the legends are correct, but that the symmetry of the interstitial has changed during relaxation (e.g. the initial structure of Pb_i_C3v relaxed to a structure with D4h symmetry). You can check this in the symmetry analysis table (e.g. with [DefectThermodynamics.get_symmetries_and_degeneracies()](https://doped.readthedocs.io/en/latest/doped.thermodynamics.html#doped.thermodynamics.DefectThermodynamics.get_symmetries_and_degeneracies))

**Comment by kavanase** [comment]
Hi Atefeh, to add to @ireaml's responses there, another likely source of the all negative formation energies (which `doped` should have warned you about when plotting) is a difference in your bulk and defect supercell calculations, whether in the inputs (in which case `doped` should also have warned you) or in the relaxed structures (e.g. octahedral tilting).

As Irea said, the grouping of defects for the formation energy plot is controlled by `dist_tol`, to avoid unnecessary duplicates and to properly separate out defect species that actually have very different sites. As shown in the [plotting & customisation tutorial](https://doped.readthedocs.io/en/latest/plotting_customisation_tutorial.html#all-entries), you can also use the `all_entries` option in plotting to see the formation energy lines for each defect charge state.

**Comment by kavanase** [comment]
Hi @Atefeh-Yadegarifard,
Has this solved your problem? I will close this issue if so.

**Comment by Atefeh-Yadegarifard** [comment]
Dear Sean and Irea, 
Thank you for your help and explanations. 
I was waiting to discuss this further with my advisor and then get back to you. Your explanations regarding plotting the intrinsic defects was very helpful. But I have been wondering about source of having negative defect formation energy as I chose a reasonably large supercell (3x3x3) with 135 atoms. however, after checking the CONTCARs, I saw quite large distortions (especially in charged cases +1 and -1). I also get the warning about large displacements by the package. I was just wondering if you have any suggestions as to how I can get the accurate defect formation energies?

**Comment by kavanase** [comment]
For your bulk supercell (with no defects), did you also try relaxing this structure? I guess there could be some large octahedral distortions taking place in this system, which artificially drop the defect supercell energies (as your bulk structure would represent a higher energy metastable state in that case).

This can be checked by just manually looking at your relaxed defect supercells in something like VESTA, and seeing how distorted the octahedra are far from the defect site, and/or using the site displacement analysis built by @ireaml for `doped` as shown [here](https://doped.readthedocs.io/en/latest/advanced_analysis_tutorial.html#defect-induced-site-displacements-strain).
There is discussion about this issue and what you can do to solve it here (if this is indeed the case):
https://shakenbreak.readthedocs.io/en/latest/Tips.html#bulk-phase-transformations

Apart from that, `doped` and `ShakeNBreak` have a number of warnings to catch sources of error that could lead to this (like the ones you mentioned there), so I would make sure not to ignore any of them, and ensure you understand what they are telling you

**Comment by aronwalsh** [comment]
The cubic perovskite structure is only stable at high temperatures. For CsPbI3 there are multiple instabilities with respect to tilting and atom displacments (e.g. https://doi.org/10.1063/1.5131575).

I suggest using the ground-state orthorhombic phase to avoid complications. These are not issues related to the doped code itself, so I will close this thread.
