### ISSUE TITLE
Application to 2D materials

### ISSUE THREAD

**Issue by Skeptikadam** [SMTG-Bham/doped#89]
Hello,

is there possible to use of this code on investigation of defects in 2D materials (graphene, TMDCs,etc)?

**Comment by kavanase** [comment]
Hi @Skeptikadam!
Yes it's possible to use `doped` to investigate defects in 2D materials, including defect generation, structure manipulation, parsing etc. You will likely want to customise certain aspects of the code and not just use the default values (which are mostly optimised for 3D solids), such as in supercell generation – where you likely want to consider the dielectric of the material you're investigating and what the optimal supercell to minimise finite-size effects is based on that, and considering what supercell choices have been used by others for similar materials, and in applying finite-size corrections – typically more specialised approaches are required for these for 2D materials (see e.g. [Kumagai 2024](https://journals.aps.org/prb/abstract/10.1103/PhysRevB.109.054106) – for which the 2D corrections code from `pydefect2d` can be used directly with the `doped` objects.

Fully automating the 2D finite-size corrections procedure is tricky as there are a few more complications compared to the 3D case, typically requiring more user input/care, but this is on the development to-do list.

**Comment by Skeptikadam** [comment]
Hi @kavanase

thank you for clear answer. I'll check it.
