### ISSUE TITLE
You can directly feed in pre-calculated chemical potentials to doped but how?

### ISSUE THREAD

**Issue by ravichinnappanphd** [SMTG-Bham/doped#92]
In the tutorials phase of doped (Defect Calculation Parsing), it is stated that "you can directly feed in pre-calculated chemical potentials to doped,.." but we are unable to see the illustration.  Suppose we want to directly feed in pre-calculated chemical potentials for 3 competing phases, say, A, B, and C, during "Defect Calculation Parsing", can you please let us have the syntax?
Thanks for the very good software tool
R

**Comment by kavanase** [comment]
Hi R,
Manually inputting chemical potentials is shown [here](https://doped.readthedocs.io/en/latest/GGA_workflow_tutorial.html#defect-formation-energy-transition-level-diagrams) and [here](https://doped.readthedocs.io/en/latest/plotting_customisation_tutorial.html#chempots-el-refs) in the tutorials. The format is also described in the docstrings and API docs (e.g. [here](https://doped.readthedocs.io/en/2.4.7/doped.thermodynamics.html#doped.thermodynamics.DefectThermodynamics)).

I'll make a clearer note of this in the tutorials. Hope that helps!

**Comment by ravichinnappanphd** [comment]
> Hi R, Manually inputting chemical potentials is shown [here](https://doped.readthedocs.io/en/latest/GGA_workflow_tutorial.html#defect-formation-energy-transition-level-diagrams) and [here](https://doped.readthedocs.io/en/latest/plotting_customisation_tutorial.html#chempots-el-refs) in the tutorials. The format is also described in the docstrings and API docs (e.g. [here](https://doped.readthedocs.io/en/2.4.7/doped.thermodynamics.html#doped.thermodynamics.DefectThermodynamics)).
> 
> I'll make a clearer note of this in the tutorials. Hope that helps!

Thanks Dr Kavanase

Can you please help me with the formation energy graph and data shown in the following screenshots?
![E_f-of-Cr-in-w-AlN](https://github.com/user-attachments/assets/76cb9bba-c8f5-4f7f-afaf-d4e80127a9b1)
![E_f-of-Cr-in-w-AlN-data](https://github.com/user-attachments/assets/de402dd3-7604-4589-b0a7-422a4e6338ee)

I can relate the 2 data points on the graph with the formation energies of Cr with charge states 0 and +1.
Does this mean the plot ignores formation energies of Cr with other charge states?
How the x-axis is obtained on the plot?
Actually, all OUTCAR's have "Fermi energy" and "E-fermi" data which are different from different OUTCAR's.
Moreover, In a given OUTCAR with Cr impurity, the "Fermi energy" and "E-fermi" themselves are different. 

The formation energy data screenshot says: "Fermi level was not set, so using mid-gap Fermi level (E_g/2=2.03 eV relative to the VBM"

How to set Fermi level to formation energy parsing?
Which Fermi level should be used, that of pure bulk or that of systems with impurity?

How to read the formation energy plot?
On the left and right sides of the 2 data points, the formation energies decrease with changes in Fermi energy?
(but no such decrease formation energies printed in the screenshot)

How to label the data points on the plot with charge states or charge transition states?
Thanks 
R
