### ISSUE TITLE
Formation energy lines..

### ISSUE THREAD

**Issue by ravichinnappanphd** [SMTG-Bham/doped#93]
Can you please tell us which python API computes "formation energy lines" and then equilibrium formation energy curve?
It is understandable how the "formation energy lines" computed from the definition of formation energy, but which API source programs this is what we are looking for.
Thanks for the help.
R.

**Comment by ireaml** [comment]
Hi @ravichinnappanphd,

Thanks for the interest in `doped`.
The formation energy plots are generated through the `plot` method of the `‎DefectThermodynamics` class in the `thermodynamics` module (https://github.com/SMTG-Bham/doped/blob/main/doped/thermodynamics.py#L2351). Within that `plot` method, it uses the internal function `_TLD_plot` (source code in the `doped.utils.plotting` module).
The usage of the  `‎DefectThermodynamics`  class is exemplified in several tutorials ([Defect Formation Energy Diagram](https://doped.readthedocs.io/en/latest/parsing_tutorial.html#defect-formation-energy-transition-level-diagrams), [Customising the Formation Energy Diagram](https://doped.readthedocs.io/en/latest/plotting_customisation_tutorial.html#defect-formation-energy-plotting)).

Best,

Irea

**Comment by kavanase** [comment]
Hi @ravichinnappanphd, as a reminder, the full code is available on the `doped` GitHub and the Python API is documented here: https://doped.readthedocs.io/en/latest/doped.html
