### ISSUE TITLE
How to save the formation energy diagram to a file?

### ISSUE THREAD

**Issue by ravichinnappanphd** [SMTG-Bham/doped#94]
plot = CdTe_example_thermo.plot(limit="Te-rich")  show the formation energy diagram on the screen when run on colab notebook.

How to save the formation energy diagram to, say, an eps file or jpg file?
The filename=xxx prints error.  What is the correct way to specify filename arg?
How to export formation energy data (which gives the formation energy diagram) to, say, agr file which can be plotted/edited with xmgrace?
Thanks
R.

**Comment by alexsquires** [comment]
Hi, 

You've correctly identified the way to save your plot, the filename argument (https://doped.readthedocs.io/en/latest/doped.thermodynamics.html#doped.thermodynamics.DefectThermodynamics.plot). This expects a PathLike object (a string will do). so you could do for example "my_formation_energy_diagram.jpg", which will save your plot as a jpeg file. Without knowing the specific error you are getting, it is difficult to say why this may not be working for you.

To edit a plot, the "intended" way for this to be done is to supply a [matplotlib style file](https://matplotlib.org/stable/users/explain/customizing.html), via the argument `style_file` in the `plot` method. If however, you would particularly like to do something custom, you may find that the `get_formation_energies` method is suitable, this will return pandas dataframes which can easily be converted to many generic file types such as csv files or jsons which should work with a range of software https://doped.readthedocs.io/en/latest/doped.thermodynamics.html#doped.thermodynamics.DefectThermodynamics.get_formation_energies

**Comment by ravichinnappanphd** [comment]
Thanks
Plot Customisation with doped tutorial helps
