### ISSUE TITLE
DefectsGenerator gives Cu_Cu antisite defects

### ISSUE THREAD

**Issue by alexsquires** [SMTG-Bham/doped#96]
version: 2.4.7

Noticed something very weird with the attached POSCAR. 

```
from pymatgen.core import Structure
from doped.generation import DefectsGenerator

structure = Structure.from_file("POSCAR")
generator = DefectsGenerator(structure)
print(generator)
```

returns, among all the defects, Cu on Cu antisites

```
Substitutions                Guessed Charges              Conv. Cell Coords    Wyckoff
---------------------------  ---------------------------  -------------------  ---------
Cu_Cu_C1_S2.24Cu3.48Cu3.53a  [+2,+1,0,-1]                 [0.247,0.176,0.415]  4b
Cu_Cu_C1_S2.24Cu3.48Cu3.53b  [+2,+1,0,-1]                 [0.247,0.176,0.415]  4b
```

Replacing the Cu with Ag, the issue goes away

```from pymatgen.core import Structure
from doped.generation import DefectsGenerator

structure = Structure.from_file("POSCAR")
structure.replace_species({"Cu": "Ag"})
generator = DefectsGenerator(structure)
print(generator)
```

or even replacing S with Se

```
from pymatgen.core import Structure
from doped.generation import DefectsGenerator

structure = Structure.from_file("POSCAR")
structure.replace_species({"S": "Se"})
generator = DefectsGenerator(structure)
print(generator)
```
[get_defects.ipynb.gz](https://github.com/user-attachments/files/17802409/get_defects.ipynb.gz)
[POSCAR.gz](https://github.com/user-attachments/files/17802410/POSCAR.gz)

**Comment by kavanase** [comment]
Good catch!
From looking now, seems to be an issue with the `pymatgen-analysis-defects` generator:
<img width="840" alt="image" src="https://github.com/user-attachments/assets/48943326-4803-43d2-8a29-d852d6d49ad0">

Digging in, I think this is because of the assignment of mixed-valence to the Cu sites here, so it identifies them as different species:
<img width="773" alt="image" src="https://github.com/user-attachments/assets/76d3bce2-923c-4353-8292-011f740679fc">

Should be a quick fix

**Comment by kavanase** [comment]
Yep found the issue, [this line](https://github.com/materialsproject/pymatgen-analysis-defects/blob/main/pymatgen/analysis/defects/generators.py#L238C9-L238C75) in `pymatgen-analysis-defects` should be `{*map(...)}` not `[*map(...)]`:
<img width="784" alt="image" src="https://github.com/user-attachments/assets/8ca5eee9-4703-45d3-9c16-145f581100e6">

**Comment by kavanase** [comment]
Fixed there ☝️
