### ISSUE TITLE
Problem with legend on transition diagram

### ISSUE THREAD

**Issue by wojtekgier** [SMTG-Bham/doped#99]
Dear all,
I met a problem with a legend on the transition diagram for a single type of defect. The legend doesn't match calculations, i.e. when number of energy lines  in the picture is increasing the legend stop to work correctly. Please, take a look at attached pictures for defects in Mg2Sn. Is there any way to fix it? Thank you.

cheers
wojtek

![Mg_Sn](https://github.com/user-attachments/assets/ac0d148b-08e4-4639-8a31-00fde54a6cae)
![Mg_Sn_-1](https://github.com/user-attachments/assets/f3aec5c6-c673-41f8-bb9f-4c9f945174d5)
![Mg_Sn_+2](https://github.com/user-attachments/assets/a29aee30-a681-4dd3-b063-f804d2a040f0)
![Mg_Sn_0](https://github.com/user-attachments/assets/6ad63907-85c6-4d1d-a5ee-af6e3b304339)

**Comment by kavanase** [comment]
Hi wojtek, 
Thanks for reporting this! We also found this minor bug a little while ago and have fixed it on the `develop` branch -- which will be merged to `main` with a new release soon. You can install this with `pip install https://github.com/SMTG-Bham/doped/archive/develop.zip`, or with `git clone` etc for the [developer installation](https://doped.readthedocs.io/en/latest/Installation.html#developer-installation).
Thanks!

**Comment by wojtekgier** [comment]
Dear Sean,

thank you.

cheers
wojtek
